GPUS: '0,1'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
TRAIN_PRINT_NUM: 6
DATASET:
  DATASET: 'ego4d'
  ROOT: '/mnt/volume2/Data/Ego4D'
  VIS_THRESHOLD: 10
  BBOX_PADDING: 20
  ORIGINAL_IMAGE_SIZE:
  - 512
  - 512
MODEL:
  NAME: 'PoolAttnHRCam_Pose_3D'
  IMAGE_SIZE:
  - 224
  - 224
  NUM_JOINTS: 21
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 34
  RECEPTIVE_FIELD: 5
  EXTRA:
    HEATMAP_SIZE:
    - 56
    - 56
    SIGMA: 2
    DEPTH_DIM: 56
    LAYERS:
      - 2
      - 2
      - 6
      - 2
    EMBED_DIMS:
      - 64
      - 128
      - 320
      - 512
    MLP_RATIOS:
      - 4
      - 4
      - 4
      - 4
    DROP_RATE: 0.1
    DROP_PATH_RATE: 0.1
LOSS:
  USE_TARGET_WEIGHT: true
TEST:
  BATCH_SIZE: 12
TRAIN:
  BATCH_SIZE: 12
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 140
  LR: 0.0001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true