OUTPUT_DIR: 'output'
GPUS: '0,1,2,3'
OUTPUT_DIR: 'output'
LOG_DIR: 'log'
WORKERS: 4
PRINT_FREQ: 500

DATASET:
  DATASET: 'freihand'
  ROOT: '/mnt/8tbvol1/FreiHand'
  TRAIN_RATIO: 0.8
  VAL_RATIO: 0.1
  TEST_RATIO: 0.1
  FLIP: true
  ROT_FACTOR: 40
  SCALE_FACTOR: 0.3
  CHUNK: 3
MODEL:
  NAME: 'PoolAttnHRCam_Pose'
  PRETRAINED: ''
  TRY_LOAD: "None"
  IMAGE_SIZE:
  - 224
  - 224
  NUM_JOINTS: 21
  NUM_DECONV_FILTERS:
  - 256
  - 256
  - 256
  NUM_LAYERS: 34
  EXTRA:
    TARGET_TYPE: 'gaussian'
    HEATMAP_SIZE:
    - 56
    - 56
    SIGMA: 2
    CROP: 'padding'
    AUGMENT: 'none'
    PRESET: 'simple_smpl_3d_cam'
    DEPTH_DIM: 64
    LAYERS:
      - 2
      - 2
      - 6
      - 2
    EMBED_DIMS:
      - 64
      - 128
      - 320
      - 512
    MLP_RATIOS:
      - 4
      - 4
      - 4
      - 4
    DROP_RATE: 0.1
    DROP_PATH_RATE: 0.1
#    PRETRAINED: "./model_files/poolattnhr_pre.pth"
    PRETRAINED: "None"
  POST:
    NORM_TYPE: 'softmax'
  BBOX_3D_SHAPE:
    - 2200
    - 2200
    - 2200
LOSS:
  USE_TARGET_WEIGHT: false
TEST:
  BATCH_SIZE: 32
  COCO_BBOX_FILE: "None"
  BBOX_THRE: 1.0
  FLIP_TEST: false
  IMAGE_THRE: 0.0
  IN_VIS_THRE: 0.2
  MODEL_FILE: ''
  NMS_THRE: 1.0
  OKS_THRE: 0.9
  USE_GT_BBOX: true
TRAIN:
  BATCH_SIZE: 24
  SHUFFLE: true
  BEGIN_EPOCH: 0
  END_EPOCH: 140
  RESUME: false
  OPTIMIZER: 'adam'
  LR: 0.001
  LR_FACTOR: 0.1
  LR_STEP:
  - 90
  - 120 
  WD: 0.0001
  GAMMA1: 0.99
  GAMMA2: 0.0
  MOMENTUM: 0.9
  NESTEROV: false
DEBUG:
  DEBUG: true
  SAVE_BATCH_IMAGES_GT: true
  SAVE_BATCH_IMAGES_PRED: true
  SAVE_HEATMAPS_GT: true
  SAVE_HEATMAPS_PRED: true